name: Run tests and publish results on PRs 🧪

on:
  pull_request:
    branches:
     - main

permissions:
  contents: read
  checks: write
  pull-requests: write

env:
  DOTNET_VERSION: "9.x"

jobs:

  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 📦
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies 📂
        run: dotnet restore CleanArchitecture.sln

      - name: Build 🧱
        run: dotnet build CleanArchitecture.sln --configuration Release --no-restore -warnaserror

      - name: Run All Tests 🧪
        run: |
            mkdir -p tests-results
            dotnet test CleanArchitecture.sln --logger "trx;LogFileName=test-results.trx" --collect:"XPlat Code Coverage" --results-directory ./tests-results
        continue-on-error: true

      - name: Publish test results 📜
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: tests-results/test-results.trx
      - name: Show Code Coverage %
        if: always()
        run: |
          coverage_file=$(find tests-results -name 'coverage.cobertura.xml' | head -n 1)

          if [ -z "$coverage_file" ]; then
              echo "❌ Aucun fichier de couverture trouvé."
              exit 0
          fi

          echo "📄 Fichier de couverture : $coverage_file"

          # Extraire l'attribut 'line-rate' du XML Cobertura
          coverage=$(xmllint --xpath "string(/coverage/@line-rate)" "$coverage_file")
          percentage=$(awk "BEGIN { printf \"%.2f\", $coverage * 100 }")

          echo "📊 **Couverture du code : $percentage%**"